
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
// Load .env.local first (Next.js convention), fallback to .env
dotenv.config({ path: ".env.local" });
dotenv.config(); // .env as fallback
import path from "node:path";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: `npx tsx ${path.join("prisma", "seed.ts")}`,
  },
  datasource: {
    // Use DIRECT_URL for migrations (port 5432, no pgbouncer)
    // Falls back to DATABASE_URL if DIRECT_URL not set
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
